In [ ]:
import kagglehub
import pandas as pd
import os

In [ ]:
path = kagglehub.dataset_download("zeeshier/student-admission-records")

Downloading to /root/.cache/kagglehub/datasets/zeeshier/student-admission-records/1.archive...

100%|██████████| 2.06k/2.06k [00:00<00:00, 2.78MB/s]

Extracting files...

In [ ]:
file_path = os.path.join(path, "student_admission_record_dirty.csv")

In [ ]:
student_data = pd.read_csv(file_path)

In [ ]:
student_data.head()

,Name,Age,Gender,Admission Test Score,High School Percentage,City,Admission Status
0,Shehroz,24.0,Female,50.0,68.90,Quetta,Rejected
1,Waqar,21.0,Female,99.0,60.73,Karachi,NaN
2,Bushra,17.0,Male,89.0,NaN,Islamabad,Accepted
3,Aliya,17.0,Male,55.0,85.29,Karachi,Rejected
4,Bilal,20.0,Male,65.0,61.13,Lahore,NaN

In [12]:
student_data

,Name,Age,Gender,Admission Test Score,High School Percentage,City,Admission Status
0,Shehroz,24.0,Female,50.0,68.90,Quetta,Rejected
1,Waqar,21.0,Female,99.0,60.73,Karachi,NaN
2,Bushra,17.0,Male,89.0,NaN,Islamabad,Accepted
3,Aliya,17.0,Male,55.0,85.29,Karachi,Rejected
4,Bilal,20.0,Male,65.0,61.13,Lahore,NaN
...,...,...,...,...,...,...,...
152,Ali,19.0,Female,85.0,78.09,Quetta,Accepted
153,Bilal,17.0,Female,81.0,84.40,Islamabad,Rejected
154,Fatima,21.0,Female,98.0,50.86,Multan,Accepted
155,Shoaib,-1.0,Male,91.0,80.12,Quetta,Accepted
156,Maaz,17.0,Male,88.0,86.85,Lahore,Accepted

In [13]:
student_data = student_data.dropna()

In [14]:
student_data = student_data.drop_duplicates()

In [15]:
student_data

,Name,Age,Gender,Admission Test Score,High School Percentage,City,Admission Status
0,Shehroz,24.0,Female,50.0,68.90,Quetta,Rejected
3,Aliya,17.0,Male,55.0,85.29,Karachi,Rejected
7,Rabia,20.0,Female,82.0,55.67,Lahore,Accepted
9,Kamran,18.0,Male,53.0,98.98,Multan,Rejected
10,Shafiq,17.0,Male,78.0,-10.00,Quetta,Rejected
...,...,...,...,...,...,...,...
152,Ali,19.0,Female,85.0,78.09,Quetta,Accepted
153,Bilal,17.0,Female,81.0,84.40,Islamabad,Rejected
154,Fatima,21.0,Female,98.0,50.86,Multan,Accepted
155,Shoaib,-1.0,Male,91.0,80.12,Quetta,Accepted
156,Maaz,17.0,Male,88.0,86.85,Lahore,Accepted

In [16]:
student_data.to_csv("student_cleaned.csv", index = False)